[JW8-11651] Implement nosnippet data attribute for error text
jwplayer/jwplayer pull request #3804
Opened 2021-01-20 20:06 UTC by zetagame

### This PR will...
Implement nosnippet data attribute for error text, preventing errored players from being indexed by search engine crawlers.

### Why is this Pull Request needed?

### Are there any points in the code the reviewer needs to double check?

### Are there any Pull Requests open in other repos which need to be merged with this?

#### Addresses Issue(s):

JW8-11651

### Checklist
- [ ] Jenkins builds and unit tests are passing
- [ ] I have reviewed the automated results

2021-01-20 20:32 UTC, jwrobot-player commented
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1704/) MULTI Build for commit d3ad7142d55046cc7252eeffa2fa4ea3a82f09db is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9058/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9058/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6071/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6071/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/27551/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/27551/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23125/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23125/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5360/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/27551/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/27551/archive/test/view/) Views

2021-01-20 22:29 UTC, robwalch requested changes

2021-01-20 22:29 UTC, robwalch commented on src/js/templates/error.ts
> +                    `<div class="jw-error-text jw-reset-text" dir="auto" data-nosnippet="">${(message || '')}<span class="jw-break jw-reset"></span>${detail}</div>` +
The empty value is unnecessary.

```suggestion
                    `<div class="jw-error-text jw-reset-text" dir="auto" data-nosnippet>${(message || '')}<span class="jw-break jw-reset"></span>${detail}</div>` +
```

2021-01-25 15:39 UTC, jwrobot-player commented
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1707/) MULTI Build for commit 42b06958f40b7f11491b7bb25084595f5011912d is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9062/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9062/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6074/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6074/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/27559/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/27559/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23133/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23133/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5367/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/27559/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/27559/archive/test/view/) Views

2021-01-25 20:35 UTC, mamaddox approved these changes

2021-01-25 20:46 UTC, robwalch approved these changes

2021-01-28 20:53 UTC, merged