[JW8-11770] Ensure wrapper is revealed when final width is set
jwplayer/jwplayer pull request #3849
Opened 2021-04-08 20:21 UTC by zetagame

### This PR will...

### Why is this Pull Request needed?

### Are there any points in the code the reviewer needs to double check?

### Are there any Pull Requests open in other repos which need to be merged with this?

#### Addresses Issue(s):

JW8-11770

### Checklist
- [ ] Jenkins builds and unit tests are passing
- [ ] I have reviewed the automated results

2021-04-08 20:53 UTC, jwrobot-player commented
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1795/) MULTI Build for commit 9dc5b83228088937f0e874542f2c969d33572688 is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9190/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9190/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6162/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6162/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28051/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28051/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23547/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23547/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5768/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28051/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28051/archive/test/view/) Views

2021-04-09 15:12 UTC, zetagame commented on src/js/view/view.js
> +            // On iOS, an ad may receive the original resize event before wrapper is revealed.
```suggestion
            // On mobile Chrome an ad may receive the original resize event before wrapper is revealed.
```

2021-04-09 15:15 UTC, jwrobot-player commented
[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1796/) MULTI Build for commit eb4b6bffe1d606f1bd113d4845c917634d923cec did not complete (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/none/consoleFull) jwplayer build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6163/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6163/consoleFull) jwplayer unit tests FAILURE
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/none/consoleFull) jwplayer-commercial unit tests NOT_STARTED
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

2021-04-09 15:18 UTC, robwalch requested changes

2021-04-09 15:18 UTC, robwalch commented on src/js/view/view.js
> +            // On iOS, an ad may receive the original resize event before wrapper is revealed.
This is a mobile UI issue, it is not specific to iOS, but to our floating implementation when either `isMobile` is true or the screen size is small.

2021-04-09 15:32 UTC, robwalch requested changes

2021-04-09 15:32 UTC, robwalch commented on src/js/view/view.js
> +            }
Why don't we avoid setting `containerWidth` and `containerHeight` to`0` while transitioning? Then when we arive at the end of the transition and are displaying again, this code can run without changes.

2021-04-09 15:46 UTC, robwalch commented on src/js/view/view.js
> +            }
https://github.com/jwplayer/jwplayer/pull/3837/files#r610730964

2021-04-09 17:28 UTC, robwalch commented
Please use #3850 instead as it fixes use of responsive listener

2021-04-09 17:28 UTC, closed without merging