[JW8-11913][JW8-11914] Click refactor bugs/improvements
jwplayer/jwplayer pull request #3885
Opened 2021-06-02 15:33 UTC by zetagame

### This PR will...
- Merge the current bugfix PRs into a single PR for testing
- Improve parity between mouse/non-mouse experience

### Why is this Pull Request needed?

### Are there any points in the code the reviewer needs to double check?

### Are there any Pull Requests open in other repos which need to be merged with this?

#### Addresses Issue(s):

JW8-11913
JW8-11914

### Checklist
- [ ] Jenkins builds and unit tests are passing
- [ ] I have reviewed the automated results

2021-06-02 16:05 UTC, robwalch requested changes

2021-06-02 16:05 UTC, robwalch commented on test/unit/ui-test.js
> -    it('triggers enter events with keyboard input', function() {
Shouldn't this be changed to `'triggers click events with keyboard input'`? the test should register `on('click'` and then the rest should be mostly the same except that we expect `type: 'click'`.

2021-06-02 16:06 UTC, robwalch approved these changes

2021-06-02 16:14 UTC, jwrobot-player commented
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1880/) MULTI Build for commit 6d12820caa2d7e7e95bff6677030668af3050d71 is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9300/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9300/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6247/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6247/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28353/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28353/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23809/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23809/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5975/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28353/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28353/archive/test/view/) Views

2021-06-02 18:42 UTC, pajong approved these changes

2021-06-03 17:37 UTC, zetagame commented
test this please

2021-06-03 18:12 UTC, jwrobot-player commented
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1882/) MULTI Build for commit 6d12820caa2d7e7e95bff6677030668af3050d71 is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9302/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9302/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6249/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6249/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28361/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28361/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23817/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23817/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5983/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28361/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28361/archive/test/view/) Views

2021-06-03 18:33 UTC, robwalch requested changes
UI is broken in the latest build. Clicking the player does not start playback.

2021-06-03 19:20 UTC, jwrobot-player commented
[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1884/) MULTI Build for commit 44041fa9613ddc4b78cf68073d99c14dbebac979 did not complete (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9305/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9305/consoleFull) jwplayer build FAILURE
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/none/consoleFull) jwplayer unit tests NOT_STARTED
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/none/consoleFull) jwplayer-commercial unit tests NOT_STARTED
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

2021-06-03 19:41 UTC, jwrobot-player commented
[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1886/) MULTI Build for commit cea0f35e39e1d57028c9195186782377ebe722cc did not complete (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9307/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9307/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6253/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6253/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23820/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23820/consoleFull) jwplayer-commercial unit tests FAILURE
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

2021-06-03 20:06 UTC, jwrobot-player commented
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1887/) MULTI Build for commit 660a49095c087ecb00ce63b447a0b803b2e4316b is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9308/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9308/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6254/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6254/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28365/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28365/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23821/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23821/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5986/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28365/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28365/archive/test/view/) Views

2021-06-03 21:46 UTC, jwrobot-player commented
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1888/) MULTI Build for commit 748027b179b34efadc9bf9b9bfba1d42f43f8eb5 is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9309/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9309/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6255/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6255/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28367/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28367/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23822/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23822/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5988/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28367/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28367/archive/test/view/) Views

2021-06-04 14:58 UTC, pajong approved these changes

2021-06-04 15:18 UTC, Diegox010 approved these changes

2021-06-04 15:28 UTC, mamaddox approved these changes

2021-06-04 18:29 UTC, jwrobot-player commented
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1890/) MULTI Build for commit 49fe84dcf856739d437b92d6e45acafe8c72a590 is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9311/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9311/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6257/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6257/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28374/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28374/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23828/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23828/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5995/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28374/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28374/archive/test/view/) Views

2021-06-04 20:53 UTC, robwalch approved these changes

2021-06-04 21:23 UTC, merged