feat: Support jw_start url query parameter which starts playback at a time
jwplayer/jwplayer pull request #3944
Opened 2021-11-23 22:31 UTC by jwbrandon

Add support for jw_start query parameter

2021-11-30 02:31 UTC, imbcmdth requested changes

2021-11-30 02:31 UTC, imbcmdth commented on src/js/controller/controller.js
> +                _seek.call(this, parseInt(searchParams.get('jw_start')));
This should probably be a `parseFloat` - nicer than including the "base" parameter to `parseInt` so that it doesn't interpret `023` as octal.

2021-11-30 17:09 UTC, esaari commented
test this please

2021-11-30 21:59 UTC, jwbrandon commented
test this please

2021-12-01 17:17 UTC, zetagame commented
Build failed

2021-12-01 17:40 UTC, jwbrandon commented
test this please

2021-12-01 17:47 UTC, imbcmdth approved these changes

2021-12-01 19:24 UTC, Dawolee approved these changes

2021-12-01 19:24 UTC, Dawolee commented on src/js/controller/controller.js
> +        const _checkAutoStart = () => {
LGTM and it works when I test it locally. However, this feature seems to only work when `autostart` is configured to `true`. Should this feature force autostart when the `jw_start` is included?

2021-12-01 19:24 UTC, Dawolee commented on src/js/controller/controller.js
> +        const _checkAutoStart = () => {
Looks like I was testing on the older PR build of jw-commercial. LGTM!

2021-12-01 20:40 UTC, jwbrandon commented on test/unit/language-test.js
> +            }
empty whitespace.

2021-12-01 20:40 UTC, jwbrandon commented on test/unit/language-test.js
> +
empty whitespace

2021-12-01 20:40 UTC, jwbrandon commented on test/unit/language-test.js
> +            });
empty whitespace

2021-12-01 21:43 UTC, jwbrandon commented
test this please

2021-12-01 23:45 UTC, jwbrandon commented
test this please

2021-12-02 17:47 UTC, zetagame approved these changes

2021-12-02 17:47 UTC, merged