[JW8-12115] Fixing menu redirect behavior after editing caption styles
jwplayer/jwplayer pull request #3970
Opened 2022-01-25 02:22 UTC by Dawolee

### This PR will...
Fix the menu redirect behavior after editing captions. It seems that at some point, the code to set the `backButtonTarget` to null was removed, which caused logic in `menuItemClick` to open the captions menu. 
### Why is this Pull Request needed?
To fix unwanted menu redirect behavior 
### Are there any points in the code the reviewer needs to double check?

### Are there any Pull Requests open in other repos which need to be merged with this?

#### Addresses Issue(s):

JW8-12115

### Checklist
- [ ] Jenkins builds and unit tests are passing
- [ ] I have reviewed the automated results

2022-01-25 17:29 UTC, zetagame requested changes

2022-01-25 17:29 UTC, zetagame commented on src/js/view/controls/components/menu/menu.js
> +            if (this.mainMenu.backButtonTarget) {
This should be in the close method of settings-menu.js

2022-01-25 18:56 UTC, zetagame approved these changes

2022-01-27 20:02 UTC, jwbrandon approved these changes

2022-01-27 20:26 UTC, merged